# Generated by Django 4.2.6 on 2023-10-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_remove_ustoz_fan_ustoz_fan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ustoz',
            name='fan',
        ),
    ]
